title: Summary of "Consumer-Based Wearable Activity Trackers Increase Physical Activity Participation- Systematic Review and Meta-Analysis"
description: |
  Page(s) created by Benkö Nathaniel, Reinprecht Alyssa
  Study by- Brickwood, K.-J., Watson, G., O’Brien, J., & Williams, A. D. (2019)
theme: jekyll-theme-cayman
plugins:
  - jekyll-remote-theme

# Site settings
url: "https://disifere.github.io"
baseurl: ""

# Navigation
nav:
  - label: Home
    url: /
  - label: Study - Al
    url: /study-al/
  - label: Study - Na
    url: /study-na/

# Collections and defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Markdown settings
markdown: kramdown
